// ─── PROFESSORS ─────────────────────────────────────────────────────
export const PROFESSORS = {
  vitalik: { name: "Prof. Vitalik Buterin", title: "Chair, Smart Contract Engineering", avatar: "VB", color: "#627EEA", bio: "Co-founder of Ethereum. One of the most respected technical and philosophical leaders in crypto, guiding Ethereum's roadmap on scalability, decentralization, and governance." },
  antonopoulos: { name: "Prof. Andreas Antonopoulos", title: "Dean of Fundamentals", avatar: "AA", color: "#F7931A", bio: "Author of Mastering Bitcoin and Mastering Ethereum. The clearest educator on cryptographic security and peer-to-peer architecture since 2012." },
  yakovenko: { name: "Prof. Anatoly Yakovenko", title: "High-Performance Systems", avatar: "AY", color: "#9945FF", bio: "Founder of Solana. Former Qualcomm OS engineer who introduced Proof of History for high-throughput blockchain transactions." },
  saylor: { name: "Prof. Michael Saylor", title: "Bitcoin Strategy & Macro", avatar: "MS", color: "#FF9500", bio: "Executive Chairman of MicroStrategy. The face of institutional Bitcoin conviction, holding one of the largest corporate BTC reserves." },
  novogratz: { name: "Prof. Mike Novogratz", title: "Institutional Investing", avatar: "MN", color: "#2D5F9A", bio: "CEO of Galaxy Digital. Former hedge fund manager bridging Wall Street and Web3 with candid macro commentary." },
  armstrong: { name: "Prof. Brian Armstrong", title: "Crypto Business & Ops", avatar: "BA", color: "#0052FF", bio: "Co-founder and CEO of Coinbase. Built one of the most regulated crypto exchanges, bridging traditional finance and crypto." },
  wood: { name: "Prof. Gavin Wood", title: "Protocol Architecture", avatar: "GW", color: "#E6007A", bio: "Co-founded Ethereum, created Solidity, then built Polkadot and the Substrate framework. A pioneer in cross-chain architecture." },
  allaire: { name: "Prof. Jeremy Allaire", title: "Stablecoins & Payments", avatar: "JA", color: "#2775CA", bio: "CEO of Circle and architect of USDC. One of the most important figures in stablecoins and crypto payments infrastructure." },
  simpson: { name: "Prof. Arianna Simpson", title: "Venture Capital & Tokens", avatar: "AS", color: "#1DB954", bio: "General Partner at a16z crypto. Leads investments across stablecoins, DeFi, and crypto infrastructure at the premier crypto VC." },
  carter: { name: "Prof. Nic Carter", title: "On-Chain Analytics", avatar: "NC", color: "#8B5CF6", bio: "Co-founded Coinmetrics and partner at Castle Island Ventures. Known for data-driven research on Bitcoin and blockchain networks." },
  cz: { name: "Prof. Changpeng Zhao", title: "Exchange Architecture", avatar: "CZ", color: "#F0B90B", bio: "Founded Binance, the world's largest crypto exchange. Now focused on Web3 ecosystem development through investments and education." },
  nailwal: { name: "Prof. Sandeep Nailwal", title: "L2 Scaling & Growth", avatar: "SN", color: "#8247E5", bio: "Co-founded Polygon (Matic), scaling it into a protocol used by Nike, Reddit, and Starbucks for mainstream blockchain adoption." },
};

// ─── CAREERS ────────────────────────────────────────────────────────
export const CAREERS = [
  { title: "Blockchain Developer", salary: "$120K–$220K", icon: "⛓️", desc: "Build smart contracts, dApps, and protocol-level code. Deep Solidity/Rust knowledge plus understanding of consensus mechanisms.", courses: ["CRYPTO101","CRYPTO201","CRYPTO202","CRYPTO203","GRAD401"], boards: ["https://crypto.jobs", "https://web3.career"] },
  { title: "DeFi Analyst / Researcher", salary: "$100K–$180K", icon: "📊", desc: "Analyze DeFi protocols, model yield strategies, assess smart contract risk, and produce on-chain research reports.", courses: ["CRYPTO301","CRYPTO303","CRYPTO102","GRAD402"], boards: ["https://crypto.jobs", "https://web3.career"] },
  { title: "Token Economist", salary: "$130K–$200K", icon: "🪙", desc: "Design tokenomics: emission schedules, governance rights, incentive structures, and mechanism design for new protocols.", courses: ["CRYPTO102","GRAD401","GRAD403"], boards: ["https://crypto.jobs", "https://angel.co/web3"] },
  { title: "Crypto Portfolio Manager", salary: "$150K–$300K+", icon: "💼", desc: "Manage institutional crypto portfolios. Requires macro thesis development, risk management, and deep market structure knowledge.", courses: ["CRYPTO102","CRYPTO303","GRAD402","GRAD501"], boards: ["https://crypto.jobs", "https://linkedin.com"] },
  { title: "Crypto VC Associate / Partner", salary: "$120K–$250K+", icon: "🚀", desc: "Evaluate early-stage crypto projects, lead due diligence, structure token investments, and support portfolio companies.", courses: ["GRAD402","GRAD403","GRAD502","CRYPTO303"], boards: ["https://crypto.jobs", "https://angel.co/web3"] },
  { title: "Protocol Engineer", salary: "$150K–$250K", icon: "🔧", desc: "Work on L1/L2 protocol design, consensus implementations, and core infrastructure. Requires deep systems knowledge.", courses: ["CRYPTO201","CRYPTO202","CRYPTO203","GRAD401"], boards: ["https://crypto.jobs", "https://web3.career"] },
  { title: "Smart Contract Auditor", salary: "$130K–$250K", icon: "🛡️", desc: "Review and audit smart contracts for vulnerabilities. Requires deep Solidity/Vyper expertise and security mindset.", courses: ["CRYPTO201","CRYPTO301","GRAD401"], boards: ["https://crypto.jobs", "https://immunefi.com"] },
  { title: "Crypto BD / Partnerships", salary: "$110K–$200K", icon: "🤝", desc: "Drive ecosystem growth through strategic partnerships, integrations, and business development for crypto companies.", courses: ["GRAD502","CRYPTO302","GRAD403","CRYPTO101"], boards: ["https://crypto.jobs", "https://web3.career"] },
  { title: "Stablecoin / Payments Lead", salary: "$130K–$220K", icon: "💵", desc: "Build or manage stablecoin products, cross-border payment rails, and fiat on/off ramps for crypto platforms.", courses: ["CRYPTO302","CRYPTO101","GRAD502","GRAD501"], boards: ["https://crypto.jobs", "https://web3.career"] },
  { title: "On-Chain Intelligence Analyst", salary: "$100K–$170K", icon: "🔍", desc: "Track whale movements, exchange flows, and network health metrics. Produce actionable intelligence from blockchain data.", courses: ["CRYPTO303","CRYPTO102","CRYPTO301"], boards: ["https://crypto.jobs", "https://chainalysis.com/careers"] },
];

// ─── CURRICULUM ──────────────────────────────────────────────────────
export const CURRICULUM = {
  undergraduate: {
    label: "Undergraduate",
    phase: "CRAWL",
    semesters: [
      {
        name: "Semester 1 — Foundations",
        courses: [
          {
            id: "CRYPTO101", code: "CRYPTO 101", title: "Introduction to Blockchain & Cryptocurrency",
            professor: "antonopoulos", credits: 4, prereqs: [],
            description: "History of money, Bitcoin whitepaper deep-dive, cryptographic primitives, consensus mechanisms, and the philosophy of decentralization.",
            modules: [
              { title: "What is Money? A Historical Perspective", type: "lecture" },
              { title: "The Bitcoin Whitepaper — Line by Line", type: "lecture" },
              { title: "Cryptographic Hash Functions & Digital Signatures", type: "lecture" },
              { title: "Proof of Work vs. Proof of Stake", type: "lecture" },
              { title: "Merkle Trees & Block Structure", type: "lecture" },
              { title: "Setting Up Your First Wallet", type: "lab" },
            ],
            readings: [
              { title: "Bitcoin: A Peer-to-Peer Electronic Cash System", url: "https://bitcoin.org/bitcoin.pdf", author: "Satoshi Nakamoto" },
              { title: "Mastering Bitcoin (Open Edition)", url: "https://github.com/bitcoinbook/bitcoinbook", author: "Andreas Antonopoulos" },
              { title: "Bitcoin Wiki — Technical Overview", url: "https://en.bitcoin.it/wiki/Main_Page", author: "Community" },
            ],
            homework: "Write a 1,500-word essay analyzing the Bitcoin whitepaper's key innovations and their real-world implications.",
            quiz: [
              { q: "What problem does the Bitcoin whitepaper primarily solve?", o: ["Double-spending without a trusted third party", "Faster credit card processing", "Cloud storage optimization", "Social media privacy"], a: 0 },
              { q: "Which cryptographic primitive secures Bitcoin transactions?", o: ["RSA encryption", "Elliptic Curve Digital Signature Algorithm (ECDSA)", "AES-256", "MD5 hashing"], a: 1 },
              { q: "What is the maximum supply of Bitcoin?", o: ["100 million", "21 million", "18.5 million", "Unlimited"], a: 1 },
              { q: "In Proof of Work, miners compete to:", o: ["Stake the most tokens", "Find a hash below a target difficulty", "Vote on transactions", "Run the fastest node"], a: 1 },
              { q: "A blockchain is best described as:", o: ["A centralized database", "A distributed append-only ledger", "A cloud computing service", "An encrypted email system"], a: 1 },
              { q: "A Merkle tree is used in Bitcoin to:", o: ["Encrypt private keys", "Efficiently verify transaction inclusion in a block", "Generate new coins", "Compress the blockchain size"], a: 1 },
              { q: "What is a nonce in Bitcoin mining?", o: ["The reward amount", "A random value miners adjust to find a valid hash", "A type of wallet address", "The transaction fee"], a: 1 },
              { q: "Bitcoin's genesis block was mined in:", o: ["2007", "2008", "2009", "2010"], a: 2 },
              { q: "A 51% attack allows an attacker to:", o: ["Steal private keys", "Reverse transactions by controlling majority hash power", "Shutdown the internet", "Create unlimited Bitcoin"], a: 1 },
              { q: "Bitcoin uses which data structure for transactions?", o: ["Account/balance model", "UTXO (Unspent Transaction Output) model", "SQL database", "Key-value store"], a: 1 },
              { q: "What happens when a block is orphaned?", o: ["All Bitcoin are lost", "The transactions return to the mempool", "The miner is banned", "The blockchain forks permanently"], a: 1 },
              { q: "The difficulty adjustment occurs approximately every:", o: ["24 hours", "1 week", "2 weeks (2,016 blocks)", "1 month"], a: 2 },
            ],
            exam: [
              { q: "Which of the following is NOT a property of a cryptographic hash function?", o: ["Deterministic output", "Reversibility", "Avalanche effect", "Fixed output size"], a: 1 },
              { q: "In the UTXO model, spending Bitcoin requires:", o: ["Updating an account balance", "Referencing unspent outputs and creating new ones", "Asking permission from miners", "Burning old tokens"], a: 1 },
              { q: "What does SPV (Simplified Payment Verification) allow?", o: ["Mining without full blocks", "Verifying transactions without downloading the full blockchain", "Creating new tokens", "Sending anonymous transactions"], a: 1 },
              { q: "The double-spending problem is fundamentally about:", o: ["Spending too much on fees", "Using the same digital token in two transactions", "Losing your private key", "Network congestion"], a: 1 },
              { q: "Bitcoin's scripting language is:", o: ["Turing-complete", "Intentionally limited and stack-based", "Object-oriented", "Based on JavaScript"], a: 1 },
              { q: "What is the purpose of the mempool?", o: ["Long-term storage of blocks", "Holding unconfirmed transactions before mining", "Encrypting wallet data", "Connecting nodes"], a: 1 },
              { q: "Nakamoto consensus resolves forks by:", o: ["Voting", "Following the longest (most work) chain", "Random selection", "Oldest node decides"], a: 1 },
              { q: "A soft fork differs from a hard fork because:", o: ["It creates a new coin", "Old nodes can still validate new blocks (backward-compatible)", "It requires all nodes to upgrade immediately", "It only affects miners"], a: 1 },
              { q: "The Bitcoin network targets a new block every:", o: ["1 minute", "5 minutes", "10 minutes", "30 minutes"], a: 2 },
              { q: "What role does the timestamp server play in the whitepaper?", o: ["It sets transaction fees", "It provides proof that data existed at a specific time", "It generates random numbers", "It stores private keys"], a: 1 },
            ],
          },
          {
            id: "CRYPTO102", code: "CRYPTO 102", title: "Digital Asset Economics",
            professor: "saylor", credits: 3, prereqs: [],
            description: "Token economics, supply/demand dynamics, inflation vs. deflation in crypto, Bitcoin as a macro asset, and portfolio theory for digital assets.",
            modules: [
              { title: "Scarcity, Stock-to-Flow, and Digital Gold", type: "lecture" },
              { title: "Token Supply Mechanics: Inflation, Burns, and Halvings", type: "lecture" },
              { title: "Bitcoin as a Macro Asset Class", type: "lecture" },
              { title: "Market Cycles, Sentiment, and Behavioral Economics", type: "lecture" },
              { title: "Portfolio Construction with Digital Assets", type: "lab" },
            ],
            readings: [
              { title: "The Bitcoin Standard", url: "https://saifedean.com/thebitcoinstandard/", author: "Saifedean Ammous" },
              { title: "MicroStrategy Bitcoin Strategy", url: "https://www.microstrategy.com/bitcoin", author: "MicroStrategy" },
              { title: "Fidelity Digital Assets Research", url: "https://www.fidelitydigitalassets.com/research-and-insights", author: "Fidelity" },
            ],
            homework: "Build a spreadsheet model comparing Bitcoin's stock-to-flow ratio against gold and silver over the past 10 years.",
            quiz: [
              { q: "Bitcoin's halving occurs approximately every:", o: ["1 year", "2 years", "4 years", "10 years"], a: 2 },
              { q: "Stock-to-flow ratio measures:", o: ["Trading volume to market cap", "Existing supply to new production rate", "Price to earnings", "Hash rate to difficulty"], a: 1 },
              { q: "A deflationary token mechanism means:", o: ["Supply increases over time", "Supply decreases or stays fixed", "Prices always go up", "Mining difficulty drops"], a: 1 },
              { q: "MicroStrategy's Bitcoin strategy is primarily based on:", o: ["Day trading", "Bitcoin as a long-term store of value superior to cash", "Staking rewards", "NFT speculation"], a: 1 },
              { q: "The Bitcoin halving affects:", o: ["Transaction speed", "Block reward given to miners", "Wallet security", "Smart contract execution"], a: 1 },
              { q: "Market capitalization is calculated as:", o: ["Total supply × price", "Circulating supply × current price", "Trading volume × 24hr change", "Hash rate × difficulty"], a: 1 },
              { q: "The 'Lindy Effect' in crypto suggests:", o: ["New coins outperform old ones", "The longer something survives, the longer it's likely to persist", "All tokens go to zero", "Only VC-backed coins succeed"], a: 1 },
              { q: "Bitcoin's monetary policy is:", o: ["Controlled by the Fed", "Algorithmically fixed and predictable", "Voted on by miners quarterly", "Adjusted by core developers"], a: 1 },
              { q: "Fully Diluted Valuation (FDV) accounts for:", o: ["Only circulating tokens", "All tokens that will ever exist × current price", "Trading volume only", "Staked tokens only"], a: 1 },
              { q: "The correlation between Bitcoin and the S&P 500:", o: ["Is always exactly 1.0", "Has varied significantly across market cycles", "Is always zero", "Is always negative"], a: 1 },
            ],
            exam: [
              { q: "Gresham's Law states that:", o: ["Good money drives out bad", "Bad money drives out good money from circulation", "All money is equal", "Digital money replaces physical"], a: 1 },
              { q: "Bitcoin's terminal inflation rate approaches:", o: ["2% annually", "0% — no new BTC after ~2140", "5% like fiat targets", "1% fixed forever"], a: 1 },
              { q: "A 'supply shock' in Bitcoin typically refers to:", o: ["A sudden price crash", "Reduced new supply from halving meeting steady/growing demand", "An exchange hack", "A protocol bug creating extra coins"], a: 1 },
              { q: "The efficient market hypothesis suggests crypto prices:", o: ["Are always correct", "Reflect all available information (debated in crypto)", "Can be easily predicted", "Only go up"], a: 1 },
              { q: "Real yield in DeFi is defined as:", o: ["Any advertised APY", "Yield generated from actual protocol revenue, not token emissions", "The highest APY available", "Yield from stablecoins only"], a: 1 },
              { q: "Network Value to Transactions (NVT) being very high suggests:", o: ["The network is undervalued", "The network may be overvalued relative to usage", "High transaction volume", "Strong fundamentals"], a: 1 },
              { q: "Dollar-cost averaging in crypto means:", o: ["Buying the dip only", "Investing fixed amounts at regular intervals regardless of price", "Going all-in at once", "Selling at fixed intervals"], a: 1 },
              { q: "Bitcoin's CAGR over its existence has been:", o: ["Negative overall", "Around 5% like bonds", "Significantly higher than any traditional asset class", "About the same as the S&P 500"], a: 2 },
            ],
          },
          {
            id: "CRYPTO103", code: "CRYPTO 103", title: "Wallet Security & Self-Custody",
            professor: "antonopoulos", credits: 2, prereqs: [],
            description: "Hot vs. cold wallets, seed phrases, multi-sig setups, operational security, and 'not your keys, not your coins.'",
            modules: [
              { title: "Types of Wallets: Hot, Cold, Hardware, Paper", type: "lecture" },
              { title: "Seed Phrases, Derivation Paths & BIP Standards", type: "lecture" },
              { title: "Multi-Signature Security Architecture", type: "lab" },
              { title: "Operational Security for Individuals and Institutions", type: "lecture" },
            ],
            readings: [
              { title: "BIP-39 Specification", url: "https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki", author: "Bitcoin Community" },
              { title: "Glacier Protocol (Cold Storage)", url: "https://glacierprotocol.org/", author: "Glacier" },
              { title: "Ledger Academy — Security", url: "https://www.ledger.com/academy", author: "Ledger" },
            ],
            homework: "Create a personal security plan for managing $100K in crypto across hot and cold storage with backup procedures.",
            quiz: [
              { q: "A seed phrase is typically:", o: ["8 words", "12 or 24 words", "A password you choose", "Your email address"], a: 1 },
              { q: "A hardware wallet stores:", o: ["Crypto coins directly", "Private keys offline", "Your exchange password", "Blockchain data"], a: 1 },
              { q: "Multi-sig (2-of-3) means:", o: ["2 passwords needed", "2 of 3 private keys must sign a transaction", "3 confirmations needed", "2 blockchains verify"], a: 1 },
              { q: "'Not your keys, not your coins' refers to:", o: ["Mining difficulty", "The risk of keeping funds on exchanges", "Token burning", "Smart contract ownership"], a: 1 },
              { q: "BIP-39 defines:", o: ["Transaction formats", "The mnemonic word list standard for seed phrases", "Exchange APIs", "Mining protocols"], a: 1 },
              { q: "A passphrase (25th word) adds:", o: ["Nothing useful", "An extra layer creating a different wallet from the same seed", "Faster transactions", "More storage"], a: 1 },
              { q: "The biggest risk of a paper wallet is:", o: ["It's too expensive", "Physical damage, loss, or theft", "Hackers can access it remotely", "It expires after one year"], a: 1 },
              { q: "HD (Hierarchical Deterministic) wallets allow:", o: ["Only one address", "Generating unlimited addresses from a single seed", "Mining faster", "Free transactions"], a: 1 },
              { q: "A $5 wrench attack refers to:", o: ["A hardware wallet defect", "Physical coercion to reveal keys", "A software vulnerability", "A network attack"], a: 1 },
              { q: "Shamir's Secret Sharing is used to:", o: ["Encrypt emails", "Split a secret into parts where a threshold is needed to reconstruct", "Speed up transactions", "Mine Bitcoin"], a: 1 },
            ],
            exam: [
              { q: "If you lose your seed phrase and your hardware wallet breaks:", o: ["The exchange can recover it", "Your funds are permanently inaccessible", "You can reset with your email", "Customer support will help"], a: 1 },
              { q: "Air-gapped signing means:", o: ["Using WiFi", "Signing transactions on a device never connected to the internet", "Cloud-based signing", "Using a VPN"], a: 1 },
              { q: "The derivation path m/44'/60'/0'/0/0 is standard for:", o: ["Bitcoin", "Ethereum", "Solana", "Dogecoin"], a: 1 },
              { q: "Social engineering attacks in crypto typically target:", o: ["The blockchain itself", "Human behavior — tricking people into revealing keys or signing malicious transactions", "Mining hardware", "Exchange servers"], a: 1 },
              { q: "For institutional custody, the gold standard is:", o: ["Hot wallet on an exchange", "Multi-sig cold storage with geographically distributed keys", "A single hardware wallet", "Printing seed phrases"], a: 1 },
              { q: "Blind signing is dangerous because:", o: ["It's slow", "You approve a transaction without verifying its contents", "It uses too much gas", "It only works on testnets"], a: 1 },
              { q: "A time-locked transaction:", o: ["Expires immediately", "Cannot be spent until a specified block height or time", "Is free", "Requires no signature"], a: 1 },
              { q: "The primary advantage of multi-sig over single-sig is:", o: ["Lower fees", "No single point of failure for key compromise", "Faster transactions", "Better privacy"], a: 1 },
            ],
          },
        ],
      },
      {
        name: "Semester 2 — Technical Literacy",
        courses: [
          {
            id: "CRYPTO201", code: "CRYPTO 201", title: "Ethereum & Smart Contracts",
            professor: "vitalik", credits: 4, prereqs: ["CRYPTO101"],
            description: "The EVM, Solidity basics, gas mechanics, the Merge, and Ethereum's roadmap (Surge, Scourge, Verge, Purge, Splurge).",
            modules: [
              { title: "EVM Architecture & State Management", type: "lecture" },
              { title: "Solidity Fundamentals: Your First Contract", type: "lab" },
              { title: "Gas, MEV, and Transaction Ordering", type: "lecture" },
              { title: "The Merge: PoW → PoS Transition", type: "lecture" },
              { title: "ERC Standards: ERC-20, ERC-721, ERC-1155", type: "lecture" },
              { title: "Ethereum's Roadmap: Scaling the World Computer", type: "lecture" },
            ],
            readings: [
              { title: "Ethereum Whitepaper", url: "https://ethereum.org/en/whitepaper/", author: "Vitalik Buterin" },
              { title: "Mastering Ethereum", url: "https://github.com/ethereumbook/ethereumbook", author: "Antonopoulos & Wood" },
              { title: "Solidity Documentation", url: "https://docs.soliditylang.org/", author: "Ethereum Foundation" },
              { title: "EVM Illustrated", url: "https://takenobu-hs.github.io/downloads/ethereum_evm_illustrated.pdf", author: "Takenobu" },
            ],
            homework: "Deploy a simple ERC-20 token on a testnet. Write a technical report on gas costs and contract interactions.",
            quiz: [
              { q: "The EVM is:", o: ["A mining rig", "A runtime environment for smart contracts", "A type of wallet", "An exchange"], a: 1 },
              { q: "Gas in Ethereum represents:", o: ["A cryptocurrency token", "Computational effort required to execute operations", "Network bandwidth", "Storage on IPFS"], a: 1 },
              { q: "The Merge transitioned Ethereum from:", o: ["PoS to PoW", "PoW to PoS", "Layer 1 to Layer 2", "ERC-20 to ERC-721"], a: 1 },
              { q: "ERC-20 is a standard for:", o: ["NFTs", "Fungible tokens", "Decentralized exchanges", "Layer 2 rollups"], a: 1 },
              { q: "MEV stands for:", o: ["Maximum Ether Value", "Maximal Extractable Value", "Miner Exchange Verification", "Multi-chain EVM Validation"], a: 1 },
              { q: "Solidity is:", o: ["A hardware description language", "A smart contract programming language for the EVM", "A database query language", "A mining algorithm"], a: 1 },
              { q: "ERC-721 tokens are:", o: ["Fungible", "Non-fungible (each token is unique)", "Stablecoins", "Governance tokens only"], a: 1 },
              { q: "The EVM is described as:", o: ["Turing-complete", "Turing-incomplete", "Stateless", "Quantum-resistant"], a: 0 },
              { q: "Ethereum's state trie stores:", o: ["Only transaction history", "Account balances, contract code, and contract storage", "Mining difficulty only", "Block headers only"], a: 1 },
              { q: "After the Merge, Ethereum block proposals are made by:", o: ["Miners with GPU rigs", "Validators who stake 32 ETH", "A central server", "Random wallet holders"], a: 1 },
              { q: "The 'Surge' in Ethereum's roadmap focuses on:", o: ["Privacy", "Scaling through rollups and sharding", "Reducing validator requirements", "Deleting old history"], a: 1 },
              { q: "A reentrancy attack exploits:", o: ["Weak passwords", "A contract calling back into the caller before state updates", "Mining pools", "DNS servers"], a: 1 },
            ],
            exam: [
              { q: "Why was EIP-1559 significant?", o: ["It enabled NFTs", "It introduced base fee burning and dynamic fee markets", "It created new tokens", "It merged PoW and PoS"], a: 1 },
              { q: "Storage on the EVM is:", o: ["Free", "The most expensive operation type due to state bloat", "Faster than computation", "Handled off-chain"], a: 1 },
              { q: "Proposer-Builder Separation (PBS) aims to:", o: ["Speed up mining", "Separate block building from block proposing to reduce MEV centralization", "Eliminate validators", "Create new token standards"], a: 1 },
              { q: "The CREATE2 opcode allows:", o: ["Destroying contracts", "Deploying contracts at deterministic addresses", "Mining ETH", "Upgrading the EVM"], a: 1 },
              { q: "Proto-danksharding (EIP-4844) introduces:", o: ["New token types", "Blob transactions to reduce rollup data costs", "A new consensus mechanism", "Account abstraction"], a: 1 },
              { q: "A proxy contract pattern is used for:", o: ["Mining", "Making contracts upgradeable by delegating calls", "Token burning", "Cross-chain transfers"], a: 1 },
              { q: "Ethereum's 'Purge' phase aims to:", o: ["Delete all ETH", "Reduce historical data nodes must store", "Remove all smart contracts", "End staking"], a: 1 },
              { q: "Account abstraction (ERC-4337) enables:", o: ["Only EOA wallets", "Smart contract wallets with features like social recovery and batched transactions", "Faster mining", "Free gas"], a: 1 },
              { q: "Slashing in PoS Ethereum penalizes validators who:", o: ["Propose too many blocks", "Act maliciously by double-signing or prolonged downtime", "Hold too much ETH", "Use old software"], a: 1 },
              { q: "The Beacon Chain's role is to:", o: ["Process transactions", "Coordinate the PoS consensus layer", "Store NFTs", "Run smart contracts"], a: 1 },
            ],
          },
          {
            id: "CRYPTO202", code: "CRYPTO 202", title: "Layer 1 Architectures Compared",
            professor: "yakovenko", credits: 3, prereqs: ["CRYPTO101"],
            description: "Comparing Solana, Ethereum, Avalanche, and more. Proof of History, parallel execution, throughput vs. decentralization tradeoffs.",
            modules: [
              { title: "The Blockchain Trilemma", type: "lecture" },
              { title: "Solana: Proof of History & Turbine", type: "lecture" },
              { title: "Avalanche Consensus & Subnets", type: "lecture" },
              { title: "Cosmos, Polkadot & Appchain Thesis", type: "lecture" },
              { title: "Benchmarking L1s: TPS, Finality, Cost", type: "lab" },
            ],
            readings: [
              { title: "Solana Whitepaper", url: "https://solana.com/solana-whitepaper.pdf", author: "Anatoly Yakovenko" },
              { title: "Avalanche Consensus Paper", url: "https://assets.website-files.com/5d80307810123f5ffbb34d6e/6009805681b416f34dcae012_Avalanche%20Consensus%20Whitepaper.pdf", author: "Team Rocket / Ava Labs" },
              { title: "Cosmos Whitepaper", url: "https://v1.cosmos.network/resources/whitepaper", author: "Tendermint" },
            ],
            homework: "Create a comparison matrix of 5 L1 blockchains across 10 technical dimensions with a recommendation memo.",
            quiz: [
              { q: "Solana's Proof of History provides:", o: ["Privacy features", "A verifiable ordering of events before consensus", "Faster mining", "Cross-chain bridges"], a: 1 },
              { q: "The blockchain trilemma states you can optimize at most:", o: ["1 of 3 properties", "2 of 3 properties", "All 3 equally", "None"], a: 1 },
              { q: "Avalanche uses which consensus family?", o: ["Nakamoto", "Classical BFT", "Snow-based probabilistic", "Proof of Authority"], a: 2 },
              { q: "Transaction finality means:", o: ["A transaction is broadcast", "A transaction is irreversibly confirmed", "A block is mined", "A wallet syncs"], a: 1 },
              { q: "Solana's Turbine protocol handles:", o: ["Consensus", "Block propagation via data shredding", "Token creation", "Wallet management"], a: 1 },
              { q: "Cosmos uses which consensus engine?", o: ["Proof of Work", "Tendermint BFT", "Snow consensus", "Proof of History"], a: 1 },
              { q: "Polkadot's parachain model allows:", o: ["Only one chain", "Multiple specialized chains sharing security from the relay chain", "Infinite TPS on one chain", "Mining-based consensus"], a: 1 },
              { q: "Solana's Sealevel runtime enables:", o: ["Single-threaded execution", "Parallel transaction processing", "Proof of Work mining", "Off-chain computation only"], a: 1 },
              { q: "Avalanche subnets are:", o: ["Mining pools", "Custom blockchain networks that can have their own rules and validators", "Layer 2 rollups", "Wallet types"], a: 1 },
              { q: "The appchain thesis argues that:", o: ["One chain should do everything", "Applications benefit from having their own dedicated blockchain", "All chains should merge", "L2s are unnecessary"], a: 1 },
            ],
            exam: [
              { q: "Solana's biggest criticism has been:", o: ["High fees", "Network outages and centralization concerns", "Lack of smart contracts", "No developer tools"], a: 1 },
              { q: "IBC (Inter-Blockchain Communication) is native to:", o: ["Ethereum", "Solana", "Cosmos ecosystem", "Avalanche"], a: 2 },
              { q: "Polkadot's shared security means:", o: ["All chains mine together", "Parachains inherit security from the relay chain validators", "One private key secures everything", "There are no validators"], a: 1 },
              { q: "Move language (used by Aptos/Sui) differs from Solidity by:", o: ["Being slower", "Offering resource-oriented programming with linear types for safer asset handling", "Not supporting smart contracts", "Only working on Bitcoin"], a: 1 },
              { q: "Solana's Gulf Stream protocol:", o: ["Handles consensus", "Forwards transactions to validators before blocks are confirmed", "Creates new tokens", "Manages staking"], a: 1 },
              { q: "Time-to-finality is critical because:", o: ["It determines token price", "Users and applications need certainty that transactions won't be reversed", "It sets mining rewards", "It determines gas costs"], a: 1 },
              { q: "Sui's object-centric model:", o: ["Is identical to Ethereum's account model", "Enables parallel processing by treating assets as independent objects", "Only supports NFTs", "Requires mining"], a: 1 },
              { q: "DAG-based consensus (used by some chains) differs from linear blockchains by:", o: ["Being centralized", "Allowing multiple blocks to be produced in parallel", "Not supporting transactions", "Requiring more storage"], a: 1 },
            ],
          },
          {
            id: "CRYPTO203", code: "CRYPTO 203", title: "Layer 2 Scaling & Rollups",
            professor: "nailwal", credits: 3, prereqs: ["CRYPTO201"],
            description: "Optimistic rollups, ZK-rollups, sidechains, Polygon's architecture, and modular blockchains.",
            modules: [
              { title: "Why Layer 2? The Scaling Imperative", type: "lecture" },
              { title: "Optimistic Rollups: Fraud Proofs", type: "lecture" },
              { title: "ZK-Rollups: Validity Proofs & Privacy", type: "lecture" },
              { title: "Polygon's Evolution: PoS → zkEVM", type: "lecture" },
              { title: "Modular Blockchains & Data Availability", type: "lecture" },
              { title: "Bridging Assets Between Layers", type: "lab" },
            ],
            readings: [
              { title: "An Incomplete Guide to Rollups", url: "https://vitalik.eth.limo/general/2021/01/05/rollup.html", author: "Vitalik Buterin" },
              { title: "Polygon zkEVM Documentation", url: "https://wiki.polygon.technology/docs/zkEVM/overview/", author: "Polygon" },
              { title: "L2Beat — L2 Analytics", url: "https://l2beat.com/", author: "L2Beat" },
            ],
            homework: "Write a technical comparison of Optimistic vs. ZK rollups with a recommendation for a hypothetical DeFi protocol.",
            quiz: [
              { q: "Optimistic rollups assume transactions are:", o: ["Invalid until proven valid", "Valid until proven fraudulent", "Always valid", "Processed off-chain only"], a: 1 },
              { q: "ZK-rollups use what to prove correctness?", o: ["Fraud proofs", "Validity proofs (zero-knowledge proofs)", "Consensus voting", "Proof of Stake"], a: 1 },
              { q: "A sidechain differs from a rollup because:", o: ["It has its own consensus/security", "It's faster", "It uses ZK proofs", "It doesn't process transactions"], a: 0 },
              { q: "The main benefit of L2 scaling is:", o: ["More decentralization", "Lower costs and higher throughput inheriting L1 security", "Replacing L1 entirely", "Eliminating gas fees"], a: 1 },
              { q: "The challenge period for optimistic rollups is typically:", o: ["1 minute", "1 hour", "7 days", "30 days"], a: 2 },
              { q: "Data availability in modular blockchains refers to:", o: ["Making websites load faster", "Ensuring transaction data is accessible for verification", "Storing files on IPFS", "Running full nodes"], a: 1 },
              { q: "Celestia's role in the modular stack is:", o: ["Execution", "Dedicated data availability layer", "Consensus for all chains", "Token issuance"], a: 1 },
              { q: "A sequencer in a rollup:", o: ["Mines blocks on L1", "Orders and batches L2 transactions before posting to L1", "Validates L1 blocks", "Creates new tokens"], a: 1 },
              { q: "zkEVM means:", o: ["A new cryptocurrency", "A ZK-rollup that is compatible with EVM bytecode/opcodes", "A mining algorithm", "A type of NFT"], a: 1 },
              { q: "Bridge security is critical because:", o: ["Bridges are always safe", "Billions have been stolen from bridge exploits due to custody of locked assets", "Bridges don't hold any funds", "L1 protects bridges automatically"], a: 1 },
            ],
            exam: [
              { q: "A validity proof (ZK) vs. fraud proof (Optimistic) — which provides faster finality?", o: ["Fraud proof (Optimistic)", "Validity proof (ZK) — no challenge period needed", "They're identical", "Neither provides finality"], a: 1 },
              { q: "Shared sequencers aim to solve:", o: ["Token supply issues", "Fragmentation and composability across multiple rollups", "Mining difficulty", "Wallet security"], a: 1 },
              { q: "EigenLayer's restaking relates to L2 security by:", o: ["Creating new tokens", "Allowing staked ETH to secure additional services and rollups", "Replacing validators", "Eliminating gas fees"], a: 1 },
              { q: "The 'rollup-centric' Ethereum roadmap means:", o: ["Ethereum will become a rollup", "Ethereum focuses on being a secure DA/settlement layer while rollups handle execution", "All rollups will merge into Ethereum", "Rollups replace Ethereum"], a: 1 },
              { q: "Forced inclusion on a rollup means:", o: ["The sequencer must include your transaction", "Users can bypass the sequencer and submit directly to L1 if censored", "All transactions are free", "Blocks are always full"], a: 1 },
              { q: "Data compression in rollups matters because:", o: ["It makes tokens cheaper", "L1 data posting is the primary cost for rollups, so smaller data = lower fees", "It speeds up consensus", "It improves privacy"], a: 1 },
              { q: "A Type 1 zkEVM differs from Type 4 by:", o: ["Type 1 is less compatible", "Type 1 is fully equivalent to Ethereum; Type 4 compiles high-level languages to ZK-friendly VMs", "Type 4 is better in all ways", "There is no difference"], a: 1 },
              { q: "Based rollups are:", o: ["The simplest rollup type", "Rollups that use L1 validators for sequencing rather than centralized sequencers", "Rollups without smart contracts", "Testing environments"], a: 1 },
            ],
          },
        ],
      },
      {
        name: "Semester 3 — Applied Knowledge",
        courses: [
          {
            id: "CRYPTO301", code: "CRYPTO 301", title: "DeFi: Decentralized Finance",
            professor: "vitalik", credits: 4, prereqs: ["CRYPTO201"],
            description: "AMMs, lending protocols, yield farming, liquidity provision, impermanent loss, and protocol risk assessment.",
            modules: [
              { title: "AMMs: Constant Product Formula & Beyond", type: "lecture" },
              { title: "Lending & Borrowing: Aave, Compound, MakerDAO", type: "lecture" },
              { title: "Yield Farming Strategies & Risk", type: "lecture" },
              { title: "Impermanent Loss: Math and Mitigation", type: "lecture" },
              { title: "Protocol Risk: Audits, TVL, Composability", type: "lecture" },
              { title: "Providing Liquidity on a DEX", type: "lab" },
            ],
            readings: [
              { title: "Uniswap V3 Whitepaper", url: "https://uniswap.org/whitepaper-v3.pdf", author: "Uniswap Labs" },
              { title: "Aave Protocol Documentation", url: "https://docs.aave.com/", author: "Aave" },
              { title: "DeFi Llama — TVL Tracker", url: "https://defillama.com/", author: "DeFi Llama" },
              { title: "Impermanent Loss Calculator", url: "https://dailydefi.org/tools/impermanent-loss-calculator/", author: "DailyDeFi" },
            ],
            homework: "Simulate providing $10K liquidity to 3 pools. Calculate impermanent loss scenarios and expected yield over 90 days.",
            quiz: [
              { q: "In a constant product AMM (x*y=k), adding more of token X:", o: ["Increases X's price", "Decreases X's price", "Has no effect", "Burns tokens"], a: 1 },
              { q: "Impermanent loss occurs when:", o: ["Gas is too high", "Token prices in a pool diverge from entry price", "A contract is hacked", "Staking rewards decrease"], a: 1 },
              { q: "Aave is primarily a:", o: ["DEX", "Lending and borrowing protocol", "NFT marketplace", "Layer 2"], a: 1 },
              { q: "TVL stands for:", o: ["Token Value Locked", "Total Value Locked", "Trading Volume Limit", "Transfer Validation Layer"], a: 1 },
              { q: "Flash loans are unique because:", o: ["They require collateral", "They must be borrowed and repaid in one transaction", "They have low interest", "They only work on Bitcoin"], a: 1 },
              { q: "Concentrated liquidity (Uniswap V3) allows:", o: ["Mining tokens", "Providing liquidity in specific price ranges for higher capital efficiency", "Free trading", "Cross-chain swaps"], a: 1 },
              { q: "A liquidation in DeFi lending occurs when:", o: ["You withdraw funds", "Your collateral value drops below the required ratio", "Gas fees are too high", "The protocol upgrades"], a: 1 },
              { q: "Composability in DeFi means:", o: ["Protocols can't interact", "Protocols can be combined like building blocks", "Everything is centralized", "Only one dApp per chain"], a: 1 },
              { q: "MakerDAO's DAI is maintained through:", o: ["A central bank", "Over-collateralized vaults (CDPs) and governance", "Mining rewards", "Exchange reserves"], a: 1 },
              { q: "Protocol-owned liquidity (POL) means:", o: ["Users own the liquidity", "The protocol itself owns its trading liquidity rather than renting it", "Liquidity is locked forever", "No one owns it"], a: 1 },
            ],
            exam: [
              { q: "The constant product formula x*y=k means:", o: ["Prices are fixed", "The product of reserve balances remains constant, determining the price curve", "Both tokens have equal value", "Trading is free"], a: 1 },
              { q: "Oracle manipulation attacks in DeFi exploit:", o: ["User passwords", "Price feed dependencies to create artificial arbitrage or liquidation opportunities", "Mining pools", "Gas limits"], a: 1 },
              { q: "The health factor in Aave represents:", o: ["Network uptime", "The ratio of collateral value to borrowed value — below 1 triggers liquidation", "Token price", "APY rate"], a: 1 },
              { q: "ve-tokenomics (vote-escrowed tokens) incentivize:", o: ["Short-term trading", "Long-term locking of tokens for governance power and enhanced yields", "Mining more tokens", "Burning all tokens"], a: 1 },
              { q: "DeFi's biggest systemic risk is:", o: ["Slow transactions", "Smart contract composability creating cascading failures across interconnected protocols", "High APYs", "Too many users"], a: 1 },
              { q: "Real yield vs. inflationary yield — the difference is:", o: ["There is none", "Real yield comes from protocol revenue; inflationary yield comes from token emissions diluting holders", "Real yield is always higher", "Inflationary yield is sustainable"], a: 1 },
              { q: "A sandwich attack in DeFi:", o: ["Steals private keys", "Front-runs and back-runs a user's swap to extract value from price impact", "Doubles your tokens", "Only affects miners"], a: 1 },
              { q: "Time-weighted average market maker (TWAMM) addresses:", o: ["NFT pricing", "Executing large orders over time to reduce price impact", "Wallet security", "Cross-chain bridges"], a: 1 },
            ],
          },
          {
            id: "CRYPTO302", code: "CRYPTO 302", title: "Stablecoins, Payments & CBDCs",
            professor: "allaire", credits: 3, prereqs: ["CRYPTO101"],
            description: "USDC, USDT, algorithmic stablecoins, the GENIUS Act, cross-border payments, and stablecoins in traditional finance.",
            modules: [
              { title: "Anatomy of a Stablecoin: Fiat-Backed vs. Algorithmic", type: "lecture" },
              { title: "USDC Architecture & Reserve Transparency", type: "lecture" },
              { title: "The GENIUS Act & Regulatory Frameworks", type: "lecture" },
              { title: "Cross-Border Payments & Remittances", type: "lecture" },
              { title: "CBDCs: Designs, Risks, and Implications", type: "lecture" },
              { title: "Integrating Stablecoin Payments", type: "lab" },
            ],
            readings: [
              { title: "Circle USDC Transparency Reports", url: "https://www.circle.com/en/transparency", author: "Circle" },
              { title: "GENIUS Act Full Text", url: "https://www.congress.gov/bill/119th-congress/senate-bill/394", author: "US Congress" },
              { title: "BIS Papers: CBDCs", url: "https://www.bis.org/about/bisih/topics/cbdc.htm", author: "Bank for International Settlements" },
            ],
            homework: "Analyze the reserve composition of 3 major stablecoins and write a risk assessment report.",
            quiz: [
              { q: "A fiat-backed stablecoin maintains its peg through:", o: ["Algorithmic adjustments", "Reserves of real-world assets backing each token", "Mining difficulty", "Governance voting"], a: 1 },
              { q: "The GENIUS Act primarily regulates:", o: ["NFTs", "Stablecoin issuers", "Mining operations", "DeFi protocols"], a: 1 },
              { q: "Algorithmic stablecoins failed (UST) because:", o: ["Too many reserves", "The peg mechanism couldn't withstand a death spiral", "Too centralized", "They were illegal"], a: 1 },
              { q: "USDC is issued by:", o: ["Tether", "Circle", "Coinbase", "MakerDAO"], a: 1 },
              { q: "Stablecoins are critical to crypto because:", o: ["They replace Bitcoin", "They provide a stable unit of account for trading, lending, and payments", "They are always profitable", "They mine new blocks"], a: 1 },
              { q: "USDT (Tether) has been criticized for:", o: ["Being too transparent", "Historical lack of clarity about reserve composition", "Not having enough users", "Being too decentralized"], a: 1 },
              { q: "A CBDC differs from a stablecoin because:", o: ["They are the same thing", "A CBDC is issued and controlled by a central bank", "CBDCs are decentralized", "CBDCs run on Bitcoin"], a: 1 },
              { q: "Cross-border remittances using stablecoins can be cheaper because:", o: ["Banks subsidize them", "They bypass traditional correspondent banking intermediaries", "They are always free", "Governments mandate low fees"], a: 1 },
              { q: "Stablecoin annual transaction volume has reached:", o: ["$1 billion", "Trillions of dollars, exceeding some payment networks", "$100 million", "Less than credit cards"], a: 1 },
              { q: "De-pegging risk means:", o: ["A stablecoin's price drifts from its target value", "A token becomes more valuable", "Mining stops", "An exchange shuts down"], a: 0 },
            ],
            exam: [
              { q: "The 'stablecoin trilemma' involves tradeoffs between:", o: ["Speed, cost, security", "Price stability, capital efficiency, and decentralization", "Privacy, speed, compliance", "Yield, risk, liquidity"], a: 1 },
              { q: "Regulatory reserves requirements for stablecoins typically mandate:", o: ["No reserves needed", "High-quality liquid assets (cash, T-bills) backing each token 1:1", "Crypto-only reserves", "Gold backing"], a: 1 },
              { q: "The UST/LUNA collapse demonstrated:", o: ["Algorithmic stablecoins are safe", "Reflexive mechanisms can create catastrophic death spirals under bank-run conditions", "All stablecoins are dangerous", "DeFi doesn't work"], a: 1 },
              { q: "Stablecoin-as-fintech overlap means:", o: ["Banks are becoming crypto companies", "Stablecoin businesses increasingly resemble traditional payment companies with transaction-based revenue", "Crypto is replacing banks entirely", "Stablecoins will disappear"], a: 1 },
              { q: "The biggest risk to privacy from CBDCs is:", o: ["They're too slow", "Government ability to surveil and potentially censor individual transactions", "They cost too much", "They don't work offline"], a: 1 },
              { q: "Yield-bearing stablecoins (like sDAI) generate returns from:", o: ["Mining", "Underlying collateral invested in T-bills or DeFi lending", "Printing new tokens", "Exchange fees only"], a: 1 },
              { q: "Stablecoin interoperability between chains is solved by:", o: ["Using one chain only", "Cross-chain bridges, native issuance on multiple chains, or protocols like CCTP", "Email transfers", "Manual conversions"], a: 1 },
              { q: "Why are banks interested in stablecoins now?", o: ["They always were", "Clearer regulation (GENIUS Act) + massive payment volumes create a viable business opportunity", "Stablecoins are going away", "Government mandates"], a: 1 },
            ],
          },
          {
            id: "CRYPTO303", code: "CRYPTO 303", title: "On-Chain Analytics & Research",
            professor: "carter", credits: 3, prereqs: ["CRYPTO102"],
            description: "Reading blockchain data, Glassnode/CryptoQuant, UTXO analysis, whale tracking, network health, and data-driven investment theses.",
            modules: [
              { title: "Reading the Blockchain: Explorers & Data Sources", type: "lecture" },
              { title: "Key On-Chain Metrics: NVT, MVRV, SOPR", type: "lecture" },
              { title: "Whale Tracking & Exchange Flow Analysis", type: "lecture" },
              { title: "Miner Economics & Hash Rate Analysis", type: "lecture" },
              { title: "Building a Dune Analytics Dashboard", type: "lab" },
            ],
            readings: [
              { title: "Glassnode Academy", url: "https://academy.glassnode.com/", author: "Glassnode" },
              { title: "Dune Analytics Documentation", url: "https://docs.dune.com/", author: "Dune" },
              { title: "CoinMetrics Research", url: "https://coinmetrics.io/insights/", author: "CoinMetrics (Nic Carter)" },
            ],
            homework: "Build a Dune dashboard tracking 3 key on-chain metrics for BTC and ETH. Present findings in a research memo.",
            quiz: [
              { q: "NVT Ratio compares:", o: ["Price to earnings", "Network value to transaction volume", "Hash rate to difficulty", "Supply to demand"], a: 1 },
              { q: "MVRV helps identify:", o: ["Mining profitability", "Whether the market is overvalued vs. realized value", "Smart contract bugs", "Token velocity"], a: 1 },
              { q: "Exchange outflows typically signal:", o: ["Selling pressure", "Accumulation (coins moving to self-custody)", "Network congestion", "A protocol upgrade"], a: 1 },
              { q: "Dune Analytics is:", o: ["A blockchain", "A query platform for on-chain data using SQL", "A DEX", "A wallet"], a: 1 },
              { q: "SOPR (Spent Output Profit Ratio) above 1 means:", o: ["Losses being realized", "On average, coins are being sold at a profit", "Network is congested", "Mining is unprofitable"], a: 1 },
              { q: "Hash rate measures:", o: ["Transaction speed", "Total computational power securing a PoW network", "Token price", "Number of wallets"], a: 1 },
              { q: "Realized cap differs from market cap by:", o: ["Using the last price each coin moved at instead of current price", "Being lower always", "Including lost coins at full value", "Being the same thing"], a: 0 },
              { q: "A 'whale alert' typically tracks:", o: ["Small transactions", "Large on-chain movements of crypto (often >$1M)", "Mining difficulty changes", "Smart contract deployments"], a: 1 },
              { q: "The UTXO age distribution shows:", o: ["Token prices", "How long coins have been held without moving — indicates holder conviction", "Mining rewards", "Exchange volumes"], a: 1 },
              { q: "Stablecoin supply ratio (SSR) measures:", o: ["Stablecoin reserves", "Bitcoin market cap relative to stablecoin market cap — potential buying power", "Exchange fees", "DeFi TVL"], a: 1 },
            ],
            exam: [
              { q: "A divergence between price and NVT signals:", o: ["Nothing useful", "Potential overvaluation (high NVT) or undervaluation (low NVT) relative to network usage", "Immediate buying opportunity", "Network failure"], a: 1 },
              { q: "Miner capitulation can be identified by:", o: ["Higher prices", "Hash rate declining + miner outflows to exchanges increasing", "More mining pools forming", "Lower gas fees"], a: 1 },
              { q: "The thermocap model values Bitcoin by:", o: ["Market sentiment", "Cumulative miner revenue — the total security spend on the network", "Trading volume only", "Social media mentions"], a: 1 },
              { q: "Entity-adjusted metrics matter because:", o: ["They look prettier", "They remove internal transfers (exchange reshuffling) to show true economic activity", "They're easier to compute", "They include more data"], a: 1 },
              { q: "A funding rate in perpetual futures being highly positive means:", o: ["Bears are dominant", "Long positions are overcrowded and paying shorts — potential correction signal", "The market is neutral", "Everyone is selling"], a: 1 },
              { q: "On-chain analysis is most useful when:", o: ["Combined with other analysis methods (technical, fundamental, macro)", "Used alone to predict prices", "Applied only to Bitcoin", "Ignored in favor of charts"], a: 0 },
              { q: "Supply in profit vs. supply in loss helps gauge:", o: ["Transaction speed", "Market sentiment extremes — high profit supply suggests euphoria; high loss supply suggests capitulation", "Mining difficulty", "Token velocity"], a: 1 },
              { q: "CryptoQuant's exchange reserve metric declining suggests:", o: ["More selling ahead", "Coins leaving exchanges, potentially reducing sell-side liquidity", "Network upgrade", "Exchange hack"], a: 1 },
            ],
          },
        ],
      },
    ],
  },
  graduate: {
    label: "Graduate School",
    phase: "RUN",
    semesters: [
      {
        name: "Semester 4 — Advanced Specialization",
        courses: [
          {
            id: "GRAD401", code: "GRAD 401", title: "Protocol Design & Mechanism Engineering",
            professor: "wood", credits: 4, prereqs: ["CRYPTO201","CRYPTO202"],
            description: "Consensus design, governance, token mechanism design, game theory, and interoperable protocol architecture.",
            modules: [
              { title: "Byzantine Fault Tolerance: Theory & Practice", type: "lecture" },
              { title: "Governance Models: On-Chain vs. Off-Chain", type: "lecture" },
              { title: "Token Mechanism Design & Game Theory", type: "lecture" },
              { title: "Cross-Chain Communication: IBC, CCIP, Bridges", type: "lecture" },
              { title: "Designing a Governance System (Capstone)", type: "lab" },
            ],
            readings: [
              { title: "Polkadot Lightpaper", url: "https://polkadot.network/Polkadot-lightpaper.pdf", author: "Gavin Wood" },
              { title: "Chainlink CCIP Docs", url: "https://docs.chain.link/ccip", author: "Chainlink" },
              { title: "Mechanism Design Theory (Nobel Lecture)", url: "https://www.nobelprize.org/prizes/economic-sciences/2007/hurwicz/lecture/", author: "Leonid Hurwicz" },
            ],
            homework: "Design a complete token mechanism for a hypothetical protocol: emission schedule, governance, staking, and incentive analysis.",
            quiz: [
              { q: "BFT ensures consensus even when:", o: ["All nodes are honest", "Up to 1/3 of nodes are malicious", "The network is offline", "Transactions are free"], a: 1 },
              { q: "On-chain governance means:", o: ["Developers decide upgrades", "Token holders vote on protocol changes via smart contracts", "A foundation decides", "Miners choose rules"], a: 1 },
              { q: "A 'dominant strategy' is:", o: ["The most profitable trade", "Optimal regardless of others' actions", "The majority vote", "The highest gas bid"], a: 1 },
              { q: "Chainlink CCIP is designed for:", o: ["L2 scaling", "Cross-chain interoperability and messaging", "NFT minting", "Stablecoin issuance"], a: 1 },
              { q: "Quadratic voting helps prevent:", o: ["Low turnout", "Plutocracy — large holders having disproportionate power", "Smart contract bugs", "Network congestion"], a: 1 },
              { q: "A bonding curve determines:", o: ["Mining difficulty", "Token price as a function of supply", "Block size", "Network latency"], a: 1 },
              { q: "Fork choice rules determine:", o: ["Token price", "Which chain tip validators should follow when forks occur", "Gas prices", "Block rewards"], a: 1 },
              { q: "Conviction voting differs from simple voting by:", o: ["Being faster", "Weighting votes by how long tokens are committed, rewarding long-term conviction", "Requiring mining", "Being off-chain only"], a: 1 },
              { q: "Substrate (Polkadot's framework) allows:", o: ["Only one chain design", "Building custom blockchains with modular, composable components", "Mining Bitcoin", "Creating NFTs only"], a: 1 },
              { q: "The principal-agent problem in DAOs refers to:", o: ["Token pricing", "Delegates potentially acting in self-interest rather than voter interest", "Network latency", "Mining pools"], a: 1 },
            ],
            exam: [
              { q: "PBFT (Practical BFT) requires how many messages per consensus round?", o: ["O(n)", "O(n²)", "O(n³)", "O(log n)"], a: 1 },
              { q: "Mechanism design is sometimes called 'reverse game theory' because:", o: ["It's backwards", "You design rules to achieve desired outcomes rather than analyzing existing games", "It eliminates strategy", "It's theoretical only"], a: 1 },
              { q: "Optimistic governance assumes:", o: ["All proposals fail", "Proposals pass unless challenged within a dispute window", "Everyone must vote", "No proposals are needed"], a: 1 },
              { q: "Token curated registries (TCRs) use economic incentives to:", o: ["Mine tokens", "Curate high-quality lists through staking and challenge mechanisms", "Create NFTs", "Set prices"], a: 1 },
              { q: "The 'nothing at stake' problem in PoS:", o: ["Validators have too much stake", "Validators can cheaply support multiple forks since there's no computational cost", "Staking is too expensive", "There are no rewards"], a: 1 },
              { q: "Retroactive public goods funding:", o: ["Funds projects before they start", "Rewards projects that have already demonstrated value, reducing speculative risk", "Is impossible on-chain", "Only funds infrastructure"], a: 1 },
              { q: "A Schelling point in crypto governance:", o: ["A technical specification", "A natural focal point where participants converge without communication", "A type of token", "A consensus algorithm"], a: 1 },
              { q: "Cross-chain message verification methods include:", o: ["Only trusted relayers", "Light client proofs, optimistic verification, ZK proofs, and multi-sig committees", "Email", "DNS lookup"], a: 1 },
            ],
          },
          {
            id: "GRAD402", code: "GRAD 402", title: "Institutional Crypto Investing",
            professor: "novogratz", credits: 4, prereqs: ["CRYPTO102","CRYPTO303"],
            description: "Portfolio construction, risk management, due diligence frameworks, fund structures, compliance, and macro thesis development.",
            modules: [
              { title: "Building a Crypto Investment Thesis", type: "lecture" },
              { title: "Risk Management: VaR, Drawdown, Correlation", type: "lecture" },
              { title: "Fund Structures: Hedge, VC, Liquid Token", type: "lecture" },
              { title: "Due Diligence Framework for Token Investments", type: "lecture" },
              { title: "Crypto ETFs and Institutional Products", type: "lecture" },
              { title: "Mock Portfolio Construction", type: "lab" },
            ],
            readings: [
              { title: "Grayscale Research Reports", url: "https://www.grayscale.com/research", author: "Grayscale" },
              { title: "a16z State of Crypto", url: "https://a16zcrypto.com/state-of-crypto/", author: "a16z crypto" },
              { title: "Galaxy Digital Research", url: "https://www.galaxy.com/research/", author: "Galaxy Digital" },
            ],
            homework: "Construct a $50M crypto fund portfolio with allocation rationale, risk limits, rebalancing strategy, and 12-month simulation.",
            quiz: [
              { q: "Sharpe Ratio measures:", o: ["Total return", "Risk-adjusted return relative to risk-free rate", "Maximum drawdown", "Volume"], a: 1 },
              { q: "A crypto VC fund typically invests in:", o: ["Public token trading only", "Early-stage equity/tokens in blockchain startups", "Bitcoin mining only", "Stablecoins only"], a: 1 },
              { q: "Due diligence should include:", o: ["Only price charts", "Team, tech, tokenomics, market, legal, and smart contract audits", "Twitter followers", "Exchange listings only"], a: 1 },
              { q: "Correlation analysis helps:", o: ["Find cheapest tokens", "Understand how assets move relative to each other for diversification", "Predict exact prices", "Mine more efficiently"], a: 1 },
              { q: "Maximum drawdown measures:", o: ["Average return", "Largest peak-to-trough decline in portfolio value", "Trading volume", "Number of positions"], a: 1 },
              { q: "A liquid token fund differs from a VC fund by:", o: ["Being illiquid", "Investing primarily in already-tradeable tokens rather than pre-launch equity", "Having no investors", "Only holding Bitcoin"], a: 1 },
              { q: "Bitcoin ETF approval was significant because:", o: ["It changed Bitcoin's code", "It gave institutional investors regulated, familiar access to BTC exposure", "It made Bitcoin faster", "It eliminated volatility"], a: 1 },
              { q: "Position sizing in crypto should account for:", o: ["Only upside potential", "Higher volatility requiring smaller positions than traditional assets", "Twitter sentiment", "Only the token's name"], a: 1 },
              { q: "Counterparty risk in crypto includes:", o: ["Weather risk", "Exchange insolvency, custodian failures, and smart contract exploits", "Competition from other investors", "Tax rates"], a: 1 },
              { q: "A crypto fund's NAV is:", o: ["A blockchain metric", "Net Asset Value — total value of holdings minus liabilities", "A consensus algorithm", "A token standard"], a: 1 },
            ],
            exam: [
              { q: "VaR (Value at Risk) at 95% confidence tells you:", o: ["Expected return", "The maximum loss not expected to be exceeded 95% of the time", "Guaranteed minimum return", "Average daily volume"], a: 1 },
              { q: "Key-man risk in a crypto fund:", o: ["Is not a real concern", "The risk that a fund depends too heavily on specific individuals", "Only applies to mining", "Is eliminated by smart contracts"], a: 1 },
              { q: "Crypto venture deal flow quality is evaluated by:", o: ["Number of deals seen", "Team pedigree, technical innovation, market timing, tokenomics quality, and competitive moat", "Token price only", "Social media hype"], a: 1 },
              { q: "Institutional custody solutions matter because:", o: ["They're cheaper", "Regulators and fiduciaries require qualified custody for client assets", "They mine faster", "They're optional"], a: 1 },
              { q: "The J-curve in crypto VC:", o: ["Doesn't exist", "Initial negative returns before portfolio companies mature and realize value", "Guaranteed profits", "A trading pattern"], a: 1 },
              { q: "Tail risk in crypto is particularly important because:", o: ["Crypto never crashes", "Extreme events (exchange collapses, depegs, hacks) occur more frequently than normal distributions predict", "It's the same as equities", "Insurance covers everything"], a: 1 },
              { q: "Rebalancing a crypto portfolio is more complex because:", o: ["Prices don't change", "24/7 markets, high volatility, tax events on each trade, and cross-chain friction", "There's only one asset", "It's fully automated"], a: 1 },
              { q: "A GP/LP structure in crypto funds:", o: ["Is unique to crypto", "Mirrors traditional fund structures — GPs manage, LPs provide capital", "Doesn't exist", "Means tokens are split 50/50"], a: 1 },
            ],
          },
          {
            id: "GRAD403", code: "GRAD 403", title: "Crypto VC & Token Launches",
            professor: "simpson", credits: 3, prereqs: ["CRYPTO102"],
            description: "Evaluating early-stage projects, SAFT/SAFE, tokenomics, airdrops, and regulatory frameworks for token distribution.",
            modules: [
              { title: "Evaluating Early-Stage Crypto Projects", type: "lecture" },
              { title: "SAFT, SAFE & Token Warrant Structures", type: "lecture" },
              { title: "Tokenomics: Vesting, Cliffs, Unlocks", type: "lecture" },
              { title: "Airdrop Strategy & Community Distribution", type: "lab" },
            ],
            readings: [
              { title: "Dragonfly State of Airdrops 2025", url: "https://www.dragonfly.xyz/research", author: "Dragonfly" },
              { title: "Electric Capital Developer Report", url: "https://www.developerreport.com/", author: "Electric Capital" },
              { title: "a16z Token Launch Guide", url: "https://a16zcrypto.com/posts/article/token-launch-legal/", author: "a16z crypto" },
            ],
            homework: "Create a tokenomics model: allocation, vesting, emission curves, and go-to-market distribution strategy.",
            quiz: [
              { q: "A SAFT is:", o: ["A type of wallet", "Simple Agreement for Future Tokens", "A staking protocol", "An audit framework"], a: 1 },
              { q: "Token vesting prevents:", o: ["Hacking", "Early investors dumping tokens immediately after launch", "Network congestion", "Smart contract bugs"], a: 1 },
              { q: "A 'cliff' in vesting means:", o: ["Tokens vest daily", "No tokens released until a specific date", "All unlocked at once", "Price drops sharply"], a: 1 },
              { q: "Airdrops serve to:", o: ["Replace mining", "Distribute tokens to early users to bootstrap network effects", "Raise capital", "Pay gas fees"], a: 1 },
              { q: "The Howey Test determines:", o: ["Token speed", "Whether a token is classified as a security under US law", "Mining difficulty", "Network capacity"], a: 1 },
              { q: "Token unlock schedules impact price because:", o: ["They don't", "Large unlocks increase available supply, potentially creating sell pressure", "They increase demand", "They burn tokens"], a: 1 },
              { q: "A token warrant gives investors:", o: ["Immediate tokens", "The right to receive tokens at a future date, often post-network launch", "Mining rights", "Governance control"], a: 1 },
              { q: "Sybil attacks on airdrops involve:", o: ["Hacking the protocol", "Creating multiple fake identities to claim more than a fair share", "Mining blocks faster", "Buying tokens on exchanges"], a: 1 },
              { q: "Progressive decentralization means:", o: ["Immediate full decentralization", "Starting with more centralized control and gradually distributing power to the community", "Never decentralizing", "Only technical decentralization"], a: 1 },
              { q: "Foundation token allocations are typically used for:", o: ["Personal profit", "Ecosystem grants, development funding, partnerships, and operational expenses", "Mining rewards only", "Burning"], a: 1 },
            ],
            exam: [
              { q: "The SEC's framework for digital assets focuses on:", o: ["Only Bitcoin", "Whether there is an 'investment of money in a common enterprise with expectation of profits from others' efforts'", "Mining difficulty", "Wallet security"], a: 1 },
              { q: "Points programs before token launches serve to:", o: ["Replace tokens entirely", "Create measurable user engagement metrics and retroactive distribution criteria", "Increase gas fees", "Mine new blocks"], a: 1 },
              { q: "Reg D / Reg S in crypto fundraising:", o: ["Are crypto-specific laws", "Traditional securities exemptions used to legally sell tokens to accredited/offshore investors", "Mining regulations", "Exchange licensing"], a: 1 },
              { q: "Low float, high FDV tokens are risky because:", o: ["They're too cheap", "Future unlock supply can create persistent selling pressure against limited circulating supply", "They're too decentralized", "They don't trade on exchanges"], a: 1 },
              { q: "The best signal for a healthy airdrop is:", o: ["Largest airdrop size", "Retention — recipients continue using the protocol after the airdrop", "Token price pumps immediately", "Celebrity endorsement"], a: 1 },
              { q: "Treasury management for a crypto project involves:", o: ["Spending all tokens immediately", "Diversifying holdings, managing runway, and avoiding market impact from sales", "Only holding Bitcoin", "Converting everything to fiat"], a: 1 },
              { q: "Due diligence red flags in early-stage crypto include:", o: ["Strong technical team", "Anonymous team, unrealistic tokenomics, no audits, forked code with no innovation", "Active GitHub", "Strong community"], a: 1 },
              { q: "Market-making agreements with projects:", o: ["Are always free", "Often involve token loans to market makers who provide liquidity in exchange for favorable terms", "Don't exist in crypto", "Are illegal"], a: 1 },
            ],
          },
        ],
      },
      {
        name: "Semester 5 — Mastery & Thesis",
        courses: [
          {
            id: "GRAD501", code: "GRAD 501", title: "Exchange Architecture & Market Making",
            professor: "cz", credits: 3, prereqs: ["CRYPTO301"],
            description: "Order books, matching engines, market making, CEX vs DEX architecture, and regulatory compliance.",
            modules: [
              { title: "Order Book Design & Matching Engines", type: "lecture" },
              { title: "Market Making: Spreads, Inventory, Risk", type: "lecture" },
              { title: "CEX vs DEX: Tradeoffs & Hybrids", type: "lecture" },
              { title: "Compliance, KYC/AML & Licensing", type: "lecture" },
              { title: "Building a Matching Engine Prototype", type: "lab" },
            ],
            readings: [
              { title: "Binance Academy", url: "https://academy.binance.com/", author: "Binance" },
              { title: "SEC Crypto Exchange Guidance", url: "https://www.sec.gov/spotlight/digital-assets", author: "SEC" },
              { title: "FATF Virtual Asset Guidance", url: "https://www.fatf-gafi.org/en/topics/virtual-assets.html", author: "FATF" },
            ],
            homework: "Design a hybrid exchange architecture combining CEX speed with DEX self-custody. Include system diagrams and compliance framework.",
            quiz: [
              { q: "A matching engine's primary function:", o: ["Store keys", "Pair buy and sell orders efficiently", "Mine blocks", "Create tokens"], a: 1 },
              { q: "Market makers profit from:", o: ["Price appreciation", "The bid-ask spread", "Mining rewards", "Governance tokens"], a: 1 },
              { q: "KYC/AML exists to:", o: ["Slow trading", "Prevent money laundering and terrorist financing", "Increase gas", "Centralize blockchain"], a: 1 },
              { q: "An order book's depth shows:", o: ["Transaction history", "Volume of buy/sell orders at various price levels", "Network hash rate", "Token supply"], a: 1 },
              { q: "A CEX's main advantage over a DEX:", o: ["Decentralization", "Speed, liquidity depth, and fiat on-ramps", "Self-custody", "Transparency"], a: 1 },
              { q: "Wash trading is:", o: ["Legitimate trading", "Artificially inflating volume by trading with yourself", "A compliance requirement", "A type of market making"], a: 1 },
              { q: "CLOB stands for:", o: ["Centralized Ledger Of Blocks", "Central Limit Order Book", "Cross-Layer Oracle Bridge", "Crypto Liquidity Operations Base"], a: 1 },
              { q: "A DEX's main advantage over a CEX:", o: ["Speed", "Non-custodial — users retain control of funds", "Higher liquidity", "Fiat support"], a: 1 },
              { q: "Price-time priority in matching means:", o: ["Largest orders first", "Best price wins; at same price, earlier order wins", "Random selection", "Miners decide order"], a: 1 },
              { q: "Proof of reserves aims to show:", o: ["Mining capacity", "An exchange holds sufficient assets to cover customer deposits", "Network decentralization", "Smart contract security"], a: 1 },
            ],
            exam: [
              { q: "Hot wallet / cold wallet ratio for an exchange balances:", o: ["Marketing spend", "Operational liquidity needs vs. security of the majority of funds", "Trading speed", "Token listings"], a: 1 },
              { q: "Market microstructure in crypto differs from TradFi because:", o: ["It's the same", "24/7 markets, fragmented liquidity across venues, and less regulatory protection create unique dynamics", "Crypto is simpler", "There are no market makers"], a: 1 },
              { q: "A circuit breaker on an exchange:", o: ["Improves connectivity", "Halts trading during extreme volatility to prevent cascading liquidations", "Speeds up matching", "Creates new tokens"], a: 1 },
              { q: "API rate limiting on exchanges serves to:", o: ["Slow down all users", "Prevent individual actors from overwhelming the system and gaining unfair advantages", "Increase fees", "Mine blocks"], a: 1 },
              { q: "Travel Rule compliance requires exchanges to:", o: ["Report all trades to media", "Share sender/receiver information for transfers above thresholds between VASPs", "Block all transactions", "Only serve US customers"], a: 1 },
              { q: "Perpetual futures on crypto exchanges differ from traditional futures by:", o: ["Being the same", "Having no expiration date, using funding rates to keep price aligned with spot", "Only trading Bitcoin", "Requiring physical delivery"], a: 1 },
              { q: "The FTX collapse highlighted:", o: ["Exchange safety", "The critical importance of segregated customer funds, proof of reserves, and regulatory oversight", "That crypto is safe", "Market efficiency"], a: 1 },
              { q: "Hybrid exchange models aim to combine:", o: ["Two blockchains", "CEX-level performance with DEX-level self-custody and transparency", "Mining and staking", "NFTs and DeFi"], a: 1 },
            ],
          },
          {
            id: "GRAD502", code: "GRAD 502", title: "Building a Crypto Business",
            professor: "armstrong", credits: 4, prereqs: ["CRYPTO101"],
            description: "From idea to IPO: building crypto companies, regulatory navigation, hiring, fundraising, and scaling.",
            modules: [
              { title: "Finding Product-Market Fit in Crypto", type: "lecture" },
              { title: "Regulatory Strategy: US, EU, Asia", type: "lecture" },
              { title: "Fundraising: Seed to Series C", type: "lecture" },
              { title: "Hiring & Culture in Web3", type: "lecture" },
              { title: "Go-to-Market for Crypto Products", type: "lecture" },
              { title: "Business Plan Workshop", type: "lab" },
            ],
            readings: [
              { title: "Coinbase S-1 Filing", url: "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001679788", author: "Coinbase / SEC" },
              { title: "Y Combinator Crypto Startup Guide", url: "https://www.ycombinator.com/library", author: "Y Combinator" },
              { title: "Messari Crypto Theses", url: "https://messari.io/crypto-theses", author: "Messari" },
            ],
            homework: "Write a complete business plan: market analysis, regulatory strategy, financials, hiring plan, and fundraising roadmap.",
            quiz: [
              { q: "PMF in crypto is best validated by:", o: ["Token price", "Organic user growth, retention, and on-chain activity", "Celebrity endorsements", "Exchange listings"], a: 1 },
              { q: "The biggest US regulatory challenge:", o: ["Mining costs", "Clarity on whether tokens are securities", "Internet speed", "Cloud hosting"], a: 1 },
              { q: "A crypto company's moat often comes from:", o: ["Patents only", "Network effects, liquidity, and developer ecosystem", "First-mover alone", "Marketing spend"], a: 1 },
              { q: "The GENIUS Act is significant because:", o: ["Bans crypto", "Provides a regulatory framework for stablecoins", "Creates government crypto", "Eliminates KYC"], a: 1 },
              { q: "MiCA (EU) regulation covers:", o: ["US companies only", "Crypto asset service providers operating in the EU", "Mining hardware", "Internet protocols"], a: 1 },
              { q: "Crypto startup hiring challenges include:", o: ["Too many candidates", "Competing with AI/tech for talent, regulatory uncertainty, and token compensation complexity", "No remote work", "Easy fundraising"], a: 1 },
              { q: "Token incentives for early users serve as:", o: ["Expensive marketing", "Customer acquisition cost (CAC) that also creates aligned stakeholders", "Regulatory requirements", "Mining rewards"], a: 1 },
              { q: "A crypto company's revenue can come from:", o: ["Only token appreciation", "Trading fees, subscription services, infrastructure fees, staking commissions, and protocol revenue", "Donations only", "Government grants"], a: 1 },
              { q: "Regulatory arbitrage in crypto means:", o: ["Breaking laws", "Strategically choosing jurisdictions with clearer, more favorable regulatory frameworks", "Avoiding all regulation", "Only operating in the US"], a: 1 },
              { q: "The biggest lesson from FTX for crypto builders:", o: ["Move fast, break things", "Corporate governance, fund segregation, and transparency are non-negotiable foundations", "Regulation is unnecessary", "Grow at all costs"], a: 1 },
            ],
            exam: [
              { q: "Pre-token, a crypto startup's valuation is based on:", o: ["Future token price", "Team, tech, TAM, traction, and competitive positioning — similar to traditional startups", "Market cap of similar tokens", "Social media following"], a: 1 },
              { q: "A dual-entity structure (US + offshore) is common because:", o: ["Tax evasion", "US entity handles fiat/compliance; offshore entity handles token operations where US rules are unclear", "It's simpler", "The SEC requires it"], a: 1 },
              { q: "Community-led growth in crypto differs from B2B SaaS growth by:", o: ["Being the same", "Relying on token-incentivized network effects, developer ecosystems, and governance participation", "Being irrelevant", "Only using advertising"], a: 1 },
              { q: "A crypto company's biggest operational risk:", o: ["Office rent", "Smart contract exploits, key management failures, or regulatory action that can threaten the entire business", "Employee vacation", "Marketing budget"], a: 1 },
              { q: "Going public (IPO/direct listing) for a crypto company requires:", o: ["Nothing special", "Strong compliance track record, audited financials, clear token-vs-equity distinction, and SEC cooperation", "Only a token launch", "Board approval only"], a: 1 },
              { q: "Crypto-native business models vs. traditional include:", o: ["No differences", "Protocol fees replacing SaaS subscriptions, token-based ownership replacing equity, and community-governed roadmaps", "Less complexity", "No revenue needed"], a: 1 },
              { q: "The 'crypto winter' survival strategy includes:", o: ["Panic selling", "Extending runway, focusing on builders over speculators, shipping product, and cutting non-essential spend", "Waiting and doing nothing", "Launching more tokens"], a: 1 },
              { q: "Embedded compliance (vs. bolt-on) means:", o: ["Ignoring regulators", "Building regulatory compliance into the product architecture from day one rather than adding it later", "Outsourcing to lawyers", "Only hiring compliance after Series B"], a: 1 },
            ],
          },
          {
            id: "THESIS", code: "GRAD 599", title: "Master's Thesis & Capstone",
            professor: "vitalik", credits: 6, prereqs: ["GRAD401","GRAD402","GRAD502"],
            description: "Original research or capstone demonstrating mastery: build a protocol, publish research, create an investment thesis, or launch a testnet product.",
            modules: [
              { title: "Thesis Proposal & Literature Review", type: "lecture" },
              { title: "Research Methodology for Crypto", type: "lecture" },
              { title: "Writing & Peer Review Workshop", type: "lab" },
              { title: "Capstone Presentation & Defense", type: "lab" },
            ],
            readings: [
              { title: "How to Write a Great Research Paper", url: "https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/", author: "Simon Peyton Jones" },
              { title: "Ethereum Research Forum", url: "https://ethresear.ch/", author: "Ethereum Community" },
              { title: "arXiv Cryptography Papers", url: "https://arxiv.org/list/cs.CR/recent", author: "Various" },
            ],
            homework: "Complete and defend your Master's Thesis or Capstone Project before a faculty panel.",
            quiz: [
              { q: "A strong crypto thesis should include:", o: ["Only price predictions", "Original analysis backed by on-chain data, technical depth, and market context", "Copy-pasted whitepapers", "Only historical charts"], a: 1 },
              { q: "Peer review helps:", o: ["Increase token price", "Validate methodology and identify blind spots", "Speed up mining", "Reduce gas fees"], a: 1 },
              { q: "A capstone project should demonstrate:", o: ["Memorization", "Applied mastery across multiple disciplines studied in the program", "Trading profits", "Social media following"], a: 1 },
              { q: "Literature review in crypto research should cover:", o: ["Only blog posts", "Academic papers, whitepapers, on-chain data, and industry reports", "Only Twitter threads", "Only news articles"], a: 1 },
              { q: "Reproducibility in crypto research means:", o: ["Copy-pasting results", "Others can verify your findings using the same data and methodology", "Using the same exchange", "Writing in the same language"], a: 1 },
              { q: "The defense presentation should:", o: ["Be as long as possible", "Clearly state the thesis, methodology, findings, and be prepared to answer rigorous questions", "Avoid questions", "Only show charts"], a: 1 },
              { q: "On-chain data as primary source material is valuable because:", o: ["It's free", "It's transparent, verifiable, and tamper-proof — stronger than self-reported data", "It's easy to manipulate", "It replaces all other sources"], a: 1 },
              { q: "A well-structured thesis contributes to the field by:", o: ["Making money", "Adding new knowledge, frameworks, or empirical evidence that advances understanding", "Being long", "Using complex jargon"], a: 1 },
              { q: "Ethical considerations in crypto research include:", o: ["None", "Disclosing conflicts of interest, token holdings, and potential market impact of findings", "Only legal compliance", "Avoiding all opinion"], a: 1 },
              { q: "The strongest capstone projects combine:", o: ["Theory only", "Technical implementation, economic analysis, and practical real-world applicability", "Only code", "Only writing"], a: 1 },
            ],
            exam: [
              { q: "A thesis that proposes a new consensus mechanism should include:", o: ["Only pseudocode", "Formal specification, security analysis, simulation results, and comparison to existing approaches", "Only a blog post", "Only price predictions"], a: 1 },
              { q: "Statistical significance in on-chain analysis:", o: ["Doesn't matter", "Ensures findings aren't due to random chance, requiring adequate sample sizes and proper methodology", "Only applies to traditional finance", "Means p > 0.5"], a: 1 },
              { q: "An investment thesis capstone should demonstrate:", o: ["Guaranteed returns", "Rigorous framework, risk analysis, position sizing rationale, and awareness of what could go wrong", "Only upside scenarios", "Copy of a famous investor's thesis"], a: 1 },
              { q: "The best crypto research bridges:", o: ["Only computer science", "Technology, economics, game theory, and real-world application — reflecting crypto's interdisciplinary nature", "Only finance", "Only mathematics"], a: 1 },
              { q: "Defending your thesis against challenges strengthens it by:", o: ["Making you defensive", "Exposing weaknesses you can address, demonstrating depth of understanding, and building rigor", "Wasting time", "Showing you can argue"], a: 1 },
            ],
          },
        ],
      },
    ],
  },
};
